### PR TITLE
Sorting the symbol index

### PR DESCRIPTION
**Pull request by czajkowskijan**
Dear Dominique,
first of all let me congratulate (and thank) you on the great package you wrote!
The main modification I did is adding a class of symbols to sort the symbol index alphabetically by labels. Two additional smaller changes are omitting warnings if noindex=yes and making the package compatible with python3 (that's thanks to @cschaffner !).
Cheers,
Jan

### CODE REVIEW

**Comment by dominique-unruh** [comment]
The parts that I reviewed so far look good and I would like to include it!

However, I have the problem that the diffs show much more changes than actually happened.

That makes it difficult to do a review of the new code.

In https://github.com/dominique-unruh/declmath/pull/1/files, a lot of lines are marked as changed due to a replacements of space by tabs, for example.

Would it be possible to do a cleanup of the code so that only those lines will show in the diff that actually changed in terms of content?

That would be great.

**Comment by czajkowskijan** [comment]
That's nice to hear.

I will try to cleanup the code a bit. Most of the changes are just white spaces, I wanted to understand the code better to avoid multiple definitions of some labels. Unfortunately I didn't manage to solve the issue, but also it's very minor.

**Comment by dominique-unruh** [comment]
> Most of the changes are just white spaces

Yes, that's what I thought. It's just that I want to be able to read through the diff to see what changed.

What do you mean by the "multiple definitions" problem?

**Comment by czajkowskijan** [comment]
Hi, I tried to clean up declmath.sty, but some whitespaces are still different. If you have any questions about the changes I made I'm happy to answer though.

As for multiple definitions, if a symbol is marked with \symbolindexmark multiple times, then it is assigned multiple times a label "\declmath@label@value". So if someone would like to refer to the marked symbol they would have to use e.g \ref{2-symbolindex}, rather than \ref{\declmath@label@value} (or what label they gave the symbol).

**Comment by dominique-unruh** [comment]
> Hi, I tried to clean up declmath.sty, but some whitespaces are still different. If you have any questions about the changes I made I'm happy to answer though.

The whitespaces are different because your editor seems to use tabs. If you replace every tab in declmath.sty by two spaces, that should fix most. By looking at the diff, you can see the result, only lines that are actually changed should show up. I would do it myself, but I cannot edit the pull request (that would need permissions as in here: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by dominique-unruh** [comment]
> As for multiple definitions, if a symbol is marked with \symbolindexmark multiple times, then it is assigned multiple times a label "\declmath@label@value". So if someone would like to refer to the marked symbol they would have to use e.g \ref{2-symbolindex}, rather than \ref{\declmath@label@value} (or what label they gave the symbol).

If I understand right, you mean the case where the **user** of the package uses `\ref{\declmath@label@value}` in the TeX source? If so, this is not something the user should do. If you want to reference a particular definition from within the document, just do something like:

```latex
\symbolindexmark{\symbol}{X}\label{symbol}
...
\pageref{symbol}
```

**Comment by czajkowskijan** [comment]
Ok, I see, but shouldn't "\label{\declmath@label@value}" in line 128 be removed then?

If I understand the code correctly, to every call of \symbolindexmark a label like "11-symbolindex" is assigned to refer to it from the index symbol (in the call to \symbolindex@writemark), but also a label \declmath@label@value is added (in line 128 in declmath.sty). I thought that this second label was meant to be used by the user. If not then maybe it's better to just omit the second label altogether.

**Comment by dominique-unruh** [comment]
> Ok, I see, but shouldn't "\label{\declmath@label@value}" in line 128 be removed then?
> 
> If I understand the code correctly, to every call of \symbolindexmark a label like "11-symbolindex" is assigned to refer to it from the index symbol (in the call to \symbolindex@writemark), but also a label \declmath@label@value is added (in line 128 in declmath.sty). I thought that this second label was meant to be used by the user. If not then maybe it's better to just omit the second label altogether.

OK, I understand now. The problematic situation is when:
* The user uses the key `label=` in the \declmath macro for some symbol
* The user has more than one occurrence of \symbolindexmark with for that symbol

(I had forgotten about `label=`)

But the key might still be a useful shortcut if there is only one \symbolindexmark. I will just add a comment to the documentation of `label=`, see dc2e1fd.

**Pull request merged**
